### ISSUE TITLE
Spikes should only summarize facts and recommenations should clearly be marked as first person

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/spikes#10]
As per the discussion in the retrospective on last Friday, we should revise the spike process to include the following:

- Spike authors are strongly encouraged to only lay out the situation as clearly and objectively as possible. A decision is to be made in a meeting where the spike is discussed.
- Recommendations for one of the proposed solutions should be clearly marked being the author's opinion

DoD: 
- Change the spike template and describe the process using ascii doc comments

**Comment by D4nte** [comment]
Do you have a spike example where this did not happen?
