### ISSUE TITLE
Prevent spike authors from forgetting about follow-up tickets

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/spikes#41]
## Problem

We have had several occasions on which we forgot to create follow-up issues after merging a spike document.

## Goal

Help spike authors to remember to create follow-up issues.

## Recommendation

Create a GitHub action that, upon merging a PR that adds a new spike to this repository:
- opens a new issue with the title "Open follow-up issues" on this repository
- assigns the spike authors (PR author?)
- moves the issue into "Sprint Backlog" of ZenHub (this will require using the ZenHub API from the action)

**Comment by bonomat** [comment]
Closed this as we should be able to do this without automation.
